### ISSUE TITLE
Chat Not Displaying

### ISSUE THREAD

**Issue by ZeroArcana** [Schkullie/ChatBubbleOverlay#1]
Absolutely nothing is displaying, no matter what I try; I just wanted something to make chat messages disappear after X seconds, but this doesn't work at all.

**Comment by Schkullie** [comment]
Hey,

sorry this wasn't working for you.
I fixed the problem (Twitch changed something and that broke my code).
If you download the code again it should work.

I also want to let you know that this was mostly a learning project for me and is not really maintained by me anymore (unless it's a quick fix).
